### ISSUE TITLE
Compatibility with ArcGIS Pro

### ISSUE THREAD

**Issue by CrispinF** [exeGesIS-SDM/GISquirrel#12]
We have been researching this for some months now, and we believe we can do it. If anyone has a clear need for this, or would like to help fund the development, please comment here.

**Comment by pgerrits19** [comment]
Hi, Any updates on the process?

**Comment by CrispinF** [comment]
@Grietz sorry we've been hugely busy on other projects, and the demand for this is far from clear. Should we take it you are interested?

**Comment by pgerrits19** [comment]
Thanks for the quick reply, I would definitely be! I believe Arcgis Pro still does not provide a solution of connecting to spatial databases (other than the Arcgis SDK or in very limited way the AGOL), so it would be a great contribution! I am by no means an expert in this, but glad to help out if needed.

**Comment by sbamberger127** [comment]
I would also be interested and I am sure many others are. I just got off the phone with an Esri sales rep and Pro can connect to a database but not edit.

**Comment by TurboGraphxBeige** [comment]
We definitely are interested in GISquirrel support for ArcGIS Pro in our organization.

**Comment by stopyaks** [comment]
I'm currently trying to figure out a way to edit postgis in ArcGIS Pro.  Sadly, it doesn't seem to exist. I'd love to see a GISquirrel version for Pro. I doubt ESRI will add this functionality anytime soon. Too busy making important functionality like "Sign in with Facebook" SMH. I'm no help with C# but I'd be happy to help test if needed.

**Comment by thelferty** [comment]
There will definitely be a need for this. My organization is looking into using GISquirrel, but we do already use ArcPro a decent amount and this is needed functionality. Not to mention it's only a matter of years before ESRI stops support for ArcGIS and migrates fully over to ArcPro. This will be a necessary enhancement for the future of GISquirrel soon enough.

**Comment by tweiss-gse** [comment]
We are also interested in this. We are currently migrating to ArcGIS Pro and GISquirrel is the only item remaining that requires us to keep using ArcMap.

**Comment by CrispinF** [comment]
@tweiss-gse have done significant work in this direction already. However, we are always struggling to prioritise this against fully funded work, and are looking for some sponsorship to complete the development. We need about 20 days funding really, i.e. £14K GBP, though smaller contributions will still get us closer to the release.
Would you, and anyone else who has commented on this issue be interested in helping us prioritise this work?

**Comment by CrispinF** [comment]
@thelferty @stopyaks @TurboGraphxBeige @sbamberger127 @pgerrits19 any interest in helping us finish and release GISquirrel for ArcGIS Pro? See previous comment re needing sponsorship for final phase of work.

**Comment by CrispinF** [comment]
Released, so closing this issue. @thelferty @stopyaks @TurboGraphxBeige @sbamberger127 @pgerrits19  please note the beta release can be downloaded https://www.gisquirrel.com/download
