### ISSUE TITLE
ArcMap Crashes When Starting to Edit With GISquirrel 

### ISSUE THREAD

**Issue by NorthBayGIS** [exeGesIS-SDM/GISquirrel#19]
When I have features selected and I start editing selected features through GISquirrel my ArcMap document crashes. 
I am using ArcMap 10.6.1 and GISquirrel v1.3.4110.0

**Comment by CrispinF** [comment]
Hi @NorthBayGIS could you give us a little more info, like:

1. Does the crash happen with _any_ feature or set of features? Or only with certain ones?
2. Has editing on this particular layer ever worked? If yes, what's changed between then and now?
3. The history of this layer? Newly imported? Created from scratch in GISquirrel?
4. Your database platform and version?
5. Could you try loading the same layer into a fresh new MXD, and try editing there?

thanks!

**Comment by NorthBayGIS** [comment]
1. It happens when more than one feature is selected and I start editing the layer with GISquirrel. It is not every time but seems to happen when multiple features are selected to edit. 
2. Yes - this is not a new layer. I have moved to a new computer with updated ArcMap. My coworker is using ArcMap 10.3.0 and can edit the same features with no issue. 
3. This is our building layer so it is  quite large and it has been around for a while. Originated as SQL table then imported with GISquirrel.  
4. SQL Server v17.8.1
5. I have tried this and experienced the same issue.

**Comment by CrispinF** [comment]
@HartmutT any thoughts?

**Comment by HartmutT** [comment]
I've tried to reproduce this with a couple of MSSQL feature classes on an ArcGIS 10.6 machine, but it wouldn't crash. I'd like to test it with a feature class that is known to have been involved in these errors, if I can get access to a copy. 
Since my test machine runs ArcGIS 10.6 there is also a possibility that 10.6.1 may behave differently. I did not have a 10.6.1 test machine at hand.

**Comment by CrispinF** [comment]
@NorthBayGIS any chance you could let us try with a copy of your database? We can provide a secure transfer mechanism if so.

**Comment by NorthBayGIS** [comment]
Hello everyone,

We have a stat holiday today and am not in the office. I will be able to get you a by 9am EDT tomorrow.(Tuesday)

One correction I would like to pint out is the answer to your question 3.
The file was loaded into ArcSQuirrel from shapefile years ago.


Sent with BlackBerry Work
(www.blackberry.com)

**Comment by CrispinF** [comment]
@NorthBayGIS are you still having any problems with this?
