### ISSUE TITLE
Error 08P01 when trying to connect to "QGIS Cloud" database

### ISSUE THREAD

**Issue by CrispinF** [exeGesIS-SDM/GISquirrel#23]
A GISquirrel user has reported that they are unable to connect to a QGIS Cloud database, with error 'ERROR: 08P01: Unsupported startup parameter: lc_monetary'.
We think this is because the version of the Npgsql connection library that GISquirrel uses to connect to PostgreSQL does not work with databases on Amazon Redshift clusters and similar.
We cannot upgrade to the very latest versions of Npgsql, as they only support .Net 4.5, whereas several GISquirrel builds need to target .Net 3.5 because that is what their target ArcGIS version supports.
We will need to look into whether there is an intermediate Npgsql verson that resolves this problem while still compatible with .Net 3.5.

**Comment by CrispinF** [comment]
@HartmutT can you confirm whether this was resolved in version v1.3.4529?  The [version history](https://www.gisquirrel.com/version-history) suggests it was, but this issue remains open with no comments.

**Comment by HartmutT** [comment]
It was not resolved in 1.3.4529, but it is now. It required some fiddling with the connection string of the initial connection used for obtaining the server's list of databases. Fortunately, the new version of the connection string works with both QGISCloud and regular PostgreSQL servers.
