### ISSUE TITLE
Feature Class Table Add Field

### ISSUE THREAD

**Issue by wyllson** [exeGesIS-SDM/GISquirrel#27]
Future enhancement of GISquirrel needs the ability to add a Field to a table.

**Comment by CrispinF** [comment]
Hi @wyllson the general philosophy of GISquirrel is that the database tables are looked after by those with an administrative role in PostgreSQL or SQL Server, where adding a field is simple if you have the privileges and tools. And any new field should appear automatically in ArcGIS through GISquirrel unless the layer is based on a view with specific field names, and that is also easy to modify.

We know that in many scenarios GISquirrel users and admins would oppose this request to be able to add new fields while working in ArcMap (which suggests it should also be possible to delete and change existing fields too) - can you provide any supporting use cases?

**Comment by wyllson** [comment]
Rural areas and small business have employees doing several jobs. My example: Our local government manages a large area  (6% of the total land size of the UK). We have two GIS people. My title is GIS Coordinator;  but i also do the Networking, GIS editing/updating, GPSing, Programming for custom apps and scripts, and now SQL database(for GISquirrel).
Our knowledge for PostgreSQL is limited to the needs of GISquirrel... New Fields wouldn't be added if the two GIS people didn't agree.

**Comment by CrispinF** [comment]
Thanks for the additional explanation.  We'll consider this request.
For now here's how to add a field to a table.  You need to use PGAdmin https://www.pgadmin.org/download/ 
In PGAdmin, browse to your table ("bank_holidays" is my table in this example) and Add Column as show in the screenshot (names of databases obscured):
![image](https://user-images.githubusercontent.com/10574730/63579490-b2f3ed80-c58a-11e9-8278-b4ea46dd8b43.png)
Then define your field, e.g. for a short text field called "street_name":
![image](https://user-images.githubusercontent.com/10574730/63579812-61982e00-c58b-11e9-8997-d5285ba528f8.png)

If your GISquirrel feature class is based on the table, the new field should magically appear in ArcMap on loading, and should be editable. Not all PG data types are compatible with ArcGIS - stick to the simple ones.

**Comment by wyllson** [comment]
Worked.........Thank you for all you help.

**Comment by CrispinF** [comment]
This is not something we want to add at this stage, so closing.
