### ISSUE TITLE
Syntax error in SQL statement that creates the domains table in the database

### ISSUE THREAD

**Issue by CrispinF** [exeGesIS-SDM/GISquirrel#30]
On connecting to a new SQL Server database in version 1.3.5071 (using ArcGIS 10.8.1) the following error is encountered:
![image](https://user-images.githubusercontent.com/10574730/121482224-d6d52d00-c9c4-11eb-92f1-b6afa51efe16.png)

**Comment by rightway1** [comment]
This issue also affects version 1.3.4698 on SQL Server 2019 using ArcGIS 10.7

**Comment by CrispinF** [comment]
Resolved in later release.
