### ISSUE TITLE
Support for PostgreSQL >= 10 scram-sha-256 authentication

### ISSUE THREAD

**Issue by HartmutT** [exeGesIS-SDM/GISquirrel#31]
PostgresSQL 10 introduced scram-sha-256 authentication, which is safer than MD5 but not supported by older client libraries. GISquirrel references version 2.2.9 of the Npgsql .Net client library, which does not support scram-sha-256. This is the latest version of Npgsql that is available for .Net 3.5, the .Net framework version targeted by ArcGIS < 10.4.
For GISquirrel builds targeting ArcGIS 10.4 and higher, this can be upgraded to Npgsql 4.09, which supports scram-sha-256. This is not the current version of Npgsql but the latest that is available for .Net 4.5.x that is targeted by recent versions of ArcGIS Desktop.

**Comment by CrispinF** [comment]
Completed and released.
